/* SomaliKing College — shared program/course data used by programs.html and program-detail.html */
window.SKC_PROGRAM_CATEGORIES = {
  'it': {
    label: 'Information Technology',
    anchor: 'faculties.html#it',
    gradient: 'from-primary-600 to-primary-900',
    icon: '<path stroke-linecap="round" stroke-linejoin="round" d="M9 17.25v1.007a3 3 0 01-.879 2.122L7.5 21h9l-.621-.621A3 3 0 0115 18.257V17.25m6-12V15a2.25 2.25 0 01-2.25 2.25H5.25A2.25 2.25 0 013 15V5.25m18 0A2.25 2.25 0 0018.75 3H5.25A2.25 2.25 0 003 5.25m18 0V12a2.25 2.25 0 01-2.25 2.25H5.25A2.25 2.25 0 013 12V5.25" />',
  },
  'engineering': {
    label: 'Engineering & Technical Studies',
    anchor: 'faculties.html#engineering',
    gradient: 'from-gold-600 to-primary-800',
    icon: '<path stroke-linecap="round" stroke-linejoin="round" d="M11.42 15.17L17.25 21A2.652 2.652 0 0021 17.25l-5.877-5.877M11.42 15.17l2.496-3.03c.317-.384.74-.626 1.208-.766M11.42 15.17l-4.655 5.653a2.548 2.548 0 11-3.586-3.586l6.837-5.63m5.108-.233c.55-.164 1.163-.188 1.743-.14a4.5 4.5 0 004.486-6.336l-3.276 3.277a3.004 3.004 0 01-2.25-2.25l3.276-3.276a4.5 4.5 0 00-6.336 4.486c.091 1.076-.071 2.264-.904 2.95l-.102.085m-1.745 1.437L5.909 7.5H4.5L2.25 3.75l1.5-1.5L7.5 4.5v1.409l4.26 4.26m-1.745 1.437l1.745-1.437m6.615 8.206L15.75 15.75M4.867 19.125h.008v.008h-.008v-.008z" />',
  },
  'social-services': {
    label: 'Social & Human Services',
    anchor: 'faculties.html#social-services',
    gradient: 'from-primary-700 to-primary-950',
    icon: '<path stroke-linecap="round" stroke-linejoin="round" d="M15 19.128a9.38 9.38 0 002.625.372 9.337 9.337 0 004.121-.952 4.125 4.125 0 00-7.533-2.493M15 19.128v-.003c0-1.113-.285-2.16-.786-3.07M15 19.128v.106A12.318 12.318 0 018.624 21c-2.331 0-4.512-.645-6.374-1.766l-.001-.109a6.375 6.375 0 0111.964-3.07M12 6.375a3.375 3.375 0 11-6.75 0 3.375 3.375 0 016.75 0zm8.25 2.25a2.625 2.625 0 11-5.25 0 2.625 2.625 0 015.25 0z" />',
  },
  'health': {
    label: 'Health Skills',
    anchor: 'faculties.html#health',
    gradient: 'from-gold-500 to-gold-700',
    icon: '<path stroke-linecap="round" stroke-linejoin="round" d="M21 8.25c0-2.485-2.099-4.5-4.688-4.5-1.935 0-3.597 1.126-4.312 2.733-.715-1.607-2.377-2.733-4.313-2.733C5.1 3.75 3 5.765 3 8.25c0 7.22 9 12 9 12s9-4.78 9-12z" />',
  },
};

window.SKC_PROGRAMS = [
  {
    slug: 'it-computer-applications',
    category: 'it',
    level: 'Certificate',
    duration: '6 Months',
    title: 'Certificate in Computer Applications',
    shortDescription: 'Word, Excel, PowerPoint, PDF workflows, and digital literacy fundamentals.',
    longDescription: 'A hands-on introduction to the software tools used in almost every modern workplace. Learners build real fluency in Microsoft Word, Excel, and PowerPoint, plus everyday digital literacy — file management, email, and working confidently with PDFs — so they can walk into an office job or run their own paperwork from day one.',
    highlights: ['Word processing, formatting, and mail merge', 'Excel formulas, tables, and basic data analysis', 'Professional slide decks with PowerPoint', 'File management, PDFs, and everyday digital literacy'],
    entryRequirements: 'Open admission — no formal prerequisites. Basic reading and writing ability in English or Somali is recommended.',
    careerOutcomes: ['Office Assistant', 'Data Entry Clerk', 'Administrative Support Officer'],
  },
  {
    slug: 'it-digital-business-support',
    category: 'it',
    level: 'Certificate',
    duration: '6 Months',
    title: 'Certificate in Digital Business Support',
    shortDescription: 'Online communication, email professionalism, and digital business tools.',
    longDescription: 'Built for learners who want to support a modern, digitally-connected business. Covers professional email and messaging etiquette, collaborative cloud tools, basic digital marketing concepts, and the everyday online workflows small and growing businesses depend on.',
    highlights: ['Professional email and business communication', 'Cloud-based collaboration tools (docs, sheets, drive)', 'Digital marketing and social media basics', 'Online scheduling, invoicing, and record-keeping tools'],
    entryRequirements: 'Open admission — no formal prerequisites. Basic reading and writing ability in English or Somali is recommended.',
    careerOutcomes: ['Digital Business Assistant', 'Social Media & Communications Support', 'Small Business Support Officer'],
  },
  {
    slug: 'it-diploma-it-support',
    category: 'it',
    level: 'Diploma',
    duration: '1–2 Years',
    title: 'Diploma in IT Support',
    shortDescription: 'Technical support, troubleshooting, networking, and web foundations.',
    longDescription: 'A deeper, practical pathway into IT as a career. Learners progress from computer applications fundamentals into hardware and software troubleshooting, networking basics, and an introduction to web technologies, building toward the kind of technical support role that keeps an organization\'s computers and network running.',
    highlights: ['PC hardware and software troubleshooting', 'Networking fundamentals (LAN, Wi-Fi, connectivity)', 'Operating systems and system maintenance', 'Introduction to websites and basic web tools'],
    entryRequirements: 'Completion of a related certificate program (e.g. Computer Applications) or equivalent practical experience is recommended.',
    careerOutcomes: ['IT Support Technician', 'Help Desk Officer', 'Network Support Assistant'],
  },
  {
    slug: 'it-advanced-diploma-applied-it',
    category: 'it',
    level: 'Advanced Diploma',
    duration: '2 Years',
    title: 'Advanced Diploma in Applied IT',
    shortDescription: 'Comprehensive IT training culminating in a digital solution portfolio project.',
    longDescription: 'SKC\'s most advanced IT pathway, combining support, networking, and applied development skills into one comprehensive program. Learners finish by designing and building a real digital solution — a website, small system, or automation tool — that becomes a portfolio piece for employment or further study.',
    highlights: ['Advanced networking and systems administration', 'Applied web and software development foundations', 'Project planning and technical documentation', 'A capstone digital solution portfolio project'],
    entryRequirements: 'Completion of the Diploma in IT Support (or equivalent) is recommended before enrolling.',
    careerOutcomes: ['Junior Systems Administrator', 'IT Officer', 'Freelance Digital Solutions Developer'],
  },

  {
    slug: 'eng-general-construction-support',
    category: 'engineering',
    level: 'Certificate',
    duration: '6–12 Months',
    title: 'Certificate in General Construction Support',
    shortDescription: 'Construction materials, workmanship, and civil works basics.',
    longDescription: 'A practical foundation in the construction trade — understanding materials, reading basic plans, safe site practices, and the workmanship standards expected on real civil works sites. Designed to prepare learners for entry-level roles on construction crews and small building projects.',
    highlights: ['Construction materials and their proper use', 'Basic site safety and workmanship standards', 'Reading simple building plans and measurements', 'Hands-on practice on real construction tasks'],
    entryRequirements: 'Open admission — no formal prerequisites. Physical capability for hands-on workshop training is required.',
    careerOutcomes: ['Construction Site Assistant', 'Building Trades Laborer', 'Site Support Worker'],
  },
  {
    slug: 'eng-electrical-solar-basics',
    category: 'engineering',
    level: 'Certificate',
    duration: '6–12 Months',
    title: 'Certificate in Electrical and Solar Basics',
    shortDescription: 'Electrical principles, basic wiring, and solar power installation.',
    longDescription: 'Covers the fundamentals of electrical work and the fast-growing field of solar power — core electrical theory, safe household and small commercial wiring, and hands-on solar panel installation and maintenance, a skillset in high demand across Puntland.',
    highlights: ['Core electrical theory and safety practices', 'Household and small commercial wiring', 'Solar panel installation and system basics', 'Testing, maintenance, and fault-finding'],
    entryRequirements: 'Open admission — no formal prerequisites. Physical capability for hands-on workshop training is required.',
    careerOutcomes: ['Electrician\'s Assistant', 'Solar Installation Technician', 'Maintenance Support Worker'],
  },
  {
    slug: 'eng-plumbing-water-systems',
    category: 'engineering',
    level: 'Certificate',
    duration: '6–12 Months',
    title: 'Certificate in Plumbing and Water Systems',
    shortDescription: 'Plumbing, water systems, and sanitation fundamentals.',
    longDescription: 'Trains learners in the plumbing and water-systems skills essential to homes, schools, and community infrastructure across Puntland — pipe work, fittings, basic water system design, and sanitation practices that support public health.',
    highlights: ['Pipe work, fittings, and basic installation', 'Water system design fundamentals', 'Sanitation and public health basics', 'Maintenance and leak/fault repair'],
    entryRequirements: 'Open admission — no formal prerequisites. Physical capability for hands-on workshop training is required.',
    careerOutcomes: ['Plumber\'s Assistant', 'Water & Sanitation Technician', 'Maintenance Support Worker'],
  },
  {
    slug: 'eng-diploma-applied-engineering',
    category: 'engineering',
    level: 'Diploma',
    duration: 'Up to 2 Years',
    title: 'Diploma in Applied Engineering Support',
    shortDescription: 'Technical drawing, surveying, estimation, and a capstone project.',
    longDescription: 'A broader technical pathway for learners aiming beyond a single trade — technical drawing, basic surveying, materials estimation, and project coordination skills, finishing with a capstone project that mirrors real engineering support work on the ground.',
    highlights: ['Technical drawing and basic surveying', 'Materials estimation and quantity take-offs', 'Project coordination fundamentals', 'A hands-on capstone engineering project'],
    entryRequirements: 'Completion of a related certificate (Construction, Electrical, or Plumbing) or equivalent practical experience is recommended.',
    careerOutcomes: ['Engineering Support Technician', 'Site Supervisor Assistant', 'Project Coordination Support'],
  },

  {
    slug: 'social-office-administration',
    category: 'social-services',
    level: 'Certificate',
    duration: '3–12 Months',
    title: 'Certificate in Office Administration & Customer Service',
    shortDescription: 'Records management, front desk professionalism, and meeting skills.',
    longDescription: 'Prepares learners for the administrative backbone of any organization — professional front-desk conduct, accurate records and filing systems, meeting coordination, and the customer service skills that keep offices, clinics, and community organizations running smoothly.',
    highlights: ['Records management and filing systems', 'Front desk and reception professionalism', 'Meeting coordination and correspondence', 'Customer service and complaint handling'],
    entryRequirements: 'Open admission — no formal prerequisites. Basic reading and writing ability in English or Somali is recommended.',
    careerOutcomes: ['Office Administrator', 'Receptionist', 'Customer Service Officer'],
  },
  {
    slug: 'social-community-development',
    category: 'social-services',
    level: 'Certificate',
    duration: '3–12 Months',
    title: 'Certificate in Community Development & Entrepreneurship',
    shortDescription: 'Community mobilization, leadership, and small business skills.',
    longDescription: 'Builds the leadership and organizing skills needed to serve and strengthen local communities — mobilizing community members around shared goals, basic project and group leadership, and the practical entrepreneurship skills to start and sustain a small business.',
    highlights: ['Community mobilization and outreach', 'Group leadership and facilitation', 'Small business planning and budgeting', 'Basic monitoring and reporting for community projects'],
    entryRequirements: 'Open admission — no formal prerequisites. Basic reading and writing ability in English or Somali is recommended.',
    careerOutcomes: ['Community Development Officer', 'NGO Field Assistant', 'Small Business Owner'],
  },

  {
    slug: 'health-community-health-support',
    category: 'health',
    level: 'Certificate',
    duration: '3–12 Months',
    title: 'Certificate in Community Health Support',
    shortDescription: 'Health promotion, nutrition, and maternal & child health awareness.',
    longDescription: 'Prepares learners to support community health outcomes at the frontline — basic health promotion messaging, nutrition awareness, and maternal and child health education that helps families in Garowe and beyond make safer, healthier choices.',
    highlights: ['Health promotion and community education', 'Nutrition basics and healthy household practices', 'Maternal and child health awareness', 'Referral pathways to formal health services'],
    entryRequirements: 'Open admission — no formal prerequisites. Basic reading and writing ability in English or Somali is recommended.',
    careerOutcomes: ['Community Health Worker', 'Health Promotion Assistant', 'NGO Health Program Support'],
  },
  {
    slug: 'health-first-aid-safety',
    category: 'health',
    level: 'Certificate',
    duration: '3–12 Months',
    title: 'Certificate in First Aid and Safety',
    shortDescription: 'Emergency response basics and safe, responsible referral.',
    longDescription: 'A practical, potentially life-saving skillset for the workplace and home — recognizing emergencies, administering basic first aid safely and confidently, and knowing when and how to refer someone to proper medical care.',
    highlights: ['Emergency recognition and initial response', 'Basic first aid and injury care', 'CPR and choking-response basics', 'Safe, responsible referral to medical services'],
    entryRequirements: 'Open admission — no formal prerequisites.',
    careerOutcomes: ['Workplace First Aid Officer', 'Community First Responder', 'Health & Safety Support Assistant'],
  },
  {
    slug: 'health-wash-hygiene-promotion',
    category: 'health',
    level: 'Certificate',
    duration: '3–12 Months',
    title: 'Certificate in WASH and Hygiene Promotion',
    shortDescription: 'Water, sanitation, and hygiene basics for homes, schools, and workplaces.',
    longDescription: 'Focused on Water, Sanitation, and Hygiene (WASH) — a field central to public health work across Puntland. Learners study safe water practices, sanitation basics, and how to promote healthy hygiene habits in homes, schools, and workplaces.',
    highlights: ['Safe water handling and storage', 'Sanitation and waste management basics', 'Hygiene promotion techniques for communities', 'WASH awareness campaigns for schools and homes'],
    entryRequirements: 'Open admission — no formal prerequisites. Basic reading and writing ability in English or Somali is recommended.',
    careerOutcomes: ['WASH Promoter', 'NGO/Public Health Field Assistant', 'Community Hygiene Educator'],
  },
];
