export enum Role {
  SUPER_ADMIN = "SUPER_ADMIN",
  ADMIN = "ADMIN",
  REGIONAL_MANAGER = "REGIONAL_MANAGER",
  BRANCH_MANAGER = "BRANCH_MANAGER",
  PROPERTY_MANAGER = "PROPERTY_MANAGER",
  AGENT = "AGENT",
  DEVELOPER = "DEVELOPER",
  OWNER = "OWNER",
  TENANT = "TENANT",
  CUSTOMER = "CUSTOMER",
  SUPPORT_STAFF = "SUPPORT_STAFF",
  ACCOUNTANT = "ACCOUNTANT",
  MARKETING_MANAGER = "MARKETING_MANAGER",
  MODERATOR = "MODERATOR",
  GUEST = "GUEST",
}

export enum PropertyType {
  APARTMENT = "APARTMENT",
  HOUSE = "HOUSE",
  VILLA = "VILLA",
  TOWNHOUSE = "TOWNHOUSE",
  DUPLEX = "DUPLEX",
  STUDIO = "STUDIO",
  PENTHOUSE = "PENTHOUSE",
  LAND = "LAND",
  FARM = "FARM",
  WAREHOUSE = "WAREHOUSE",
  OFFICE = "OFFICE",
  RETAIL = "RETAIL",
  HOTEL = "HOTEL",
  HOSTEL = "HOSTEL",
  INDUSTRIAL = "INDUSTRIAL",
  MIXED_USE = "MIXED_USE",
  RESTAURANT = "RESTAURANT",
  SHOP = "SHOP",
  HOSPITAL = "HOSPITAL",
  SCHOOL = "SCHOOL",
  BUILDING = "BUILDING",
  RESORT = "RESORT",
  VACATION_HOME = "VACATION_HOME",
}

export enum ListingType {
  SALE = "SALE",
  RENT = "RENT",
  COMMERCIAL = "COMMERCIAL",
}

export enum PropertyStatus {
  DRAFT = "DRAFT",
  PENDING_REVIEW = "PENDING_REVIEW",
  PUBLISHED = "PUBLISHED",
  UNDER_OFFER = "UNDER_OFFER",
  SOLD = "SOLD",
  RENTED = "RENTED",
  ARCHIVED = "ARCHIVED",
  REJECTED = "REJECTED",
}

export enum FurnishingStatus {
  UNFURNISHED = "UNFURNISHED",
  SEMI_FURNISHED = "SEMI_FURNISHED",
  FURNISHED = "FURNISHED",
}

export enum BookingStatus {
  PENDING = "PENDING",
  CONFIRMED = "CONFIRMED",
  CANCELLED = "CANCELLED",
  RESCHEDULED = "RESCHEDULED",
  COMPLETED = "COMPLETED",
  NO_SHOW = "NO_SHOW",
}

export enum PaymentGatewayProvider {
  STRIPE = "STRIPE",
  PAYPAL = "PAYPAL",
  HORMUUD_EVC = "HORMUUD_EVC",
  ZAAD = "ZAAD",
  SAHAL = "SAHAL",
  PREMIER_WALLET = "PREMIER_WALLET",
}

export enum PaymentStatus {
  PENDING = "PENDING",
  PROCESSING = "PROCESSING",
  SUCCEEDED = "SUCCEEDED",
  FAILED = "FAILED",
  REFUNDED = "REFUNDED",
  CANCELLED = "CANCELLED",
}

export enum InvoiceStatus {
  DRAFT = "DRAFT",
  SENT = "SENT",
  PAID = "PAID",
  OVERDUE = "OVERDUE",
  VOID = "VOID",
}

export enum NotificationChannel {
  EMAIL = "EMAIL",
  SMS = "SMS",
  PUSH = "PUSH",
  WHATSAPP = "WHATSAPP",
  IN_APP = "IN_APP",
}

export enum SupportTicketStatus {
  OPEN = "OPEN",
  IN_PROGRESS = "IN_PROGRESS",
  RESOLVED = "RESOLVED",
  CLOSED = "CLOSED",
}

export enum SupportTicketPriority {
  LOW = "LOW",
  MEDIUM = "MEDIUM",
  HIGH = "HIGH",
  URGENT = "URGENT",
}
